<div class="content-header">
    <table cellspacing="0">
        <tbody>
            <tr>
                <td style="width:50%;">
                    <h3 class="icon-head head-report-product-sold">Sales Report</h3>
                </td>
                <td class="form-buttons"></td>
            </tr>
        </tbody>
    </table>
</div>

<div>

    <?php // Filter By Date Range ?>
    <div class="entry-edit">
        <div class="fieldset" style="overflow: hidden;">
            <div class="f-left" style="margin-right: 11px;">
                <div id="salesmanagerment-report-month">
                    <label for="report_month"><?php echo $this->__('Month') ?>: </label>
                    <select id="report_month" name="month">
                        <?php
                        for($i = 1; $i <=12; $i++) {
                            echo '<option value="'.$i.'">'. "Tháng " . $i .'</option>';
                        }
                        ?>
                    </select>
                </div>
            </div>
            <div class="f-left" style="margin-right: 11px;">
                <div id="salesmanagerment-report-year">
                    <label for="report_year"><?php echo $this->__('Year') ?>: </label>
                    <select id="report_year" name="year">
                        <?php
                        for($i = 2016; $i <=2050; $i++) {
                            echo '<option value="'.$i.'">'. $i .'</option>';
                        }
                        ?>
                    </select>
                </div>
            </div>
            <button id="id_<?php echo microtime() ?>" type="button" class="scalable task" onclick="<?php echo $this->getJsObjectName() ?>.doFilter()">
                <span><?php echo $this->__('Show Report') ?></span>
            </button>
        </div>
    </div>

    <?php echo $this->getChildHtml('salesreport_content') ?>
</div>

<script type="text/javascript">
    <?php echo $this->getJsObjectName() ?>.doFilter = function()
    {
        var filters = $$('#'+this.containerId+' .filter input', '#'+this.containerId+' .filter select', '#report_month', '#report_year');
        var elements = [];
        for(var i in filters){
            if(filters[i].value && filters[i].value.length) elements.push(filters[i]);
        }
        if (!this.doFilterCallback || (this.doFilterCallback && this.doFilterCallback())) {
            this.reload(this.addVarToUrl(this.filterVar, encode_base64(Form.serializeElements(elements))));
        }
    }
    
    <?php echo $this->getJsObjectName() ?>.resetFilter = function()
    {
        var filters = $$('#report_month', '#report_year');
        var elements = [];
        for(var i in filters){
            if(filters[i].value && filters[i].value.length) elements.push(filters[i]);
        }
        if (!this.doFilterCallback || (this.doFilterCallback && this.doFilterCallback())) {
            this.reload(this.addVarToUrl(this.filterVar, encode_base64(Form.serializeElements(elements))));
        }
    }
</script>
